### ISSUE TITLE
Test suite removed just prior to 1.0 release?

### ISSUE THREAD

**Issue by marshall007** [loadfive/Knwl.js#66]
It appears that all the tests were removed in 7fd3637, was there a reason behind this? It would be much easier to write plugins if we had example test cases for the existing default ones.

**Comment by benjojo** [comment]
Oh. :( I spent a lot of time on those

**Comment by loadfive** [comment]
Sorry about that. They'll be back up in just a bit.

**Comment by loadfive** [comment]
Alright! They've been pushed back up. They may not be entirely compatible with the current version of Knwl.js, as some formatting has changed, but I made a few changes to try and ensure they do work.
