### ISSUE TITLE
russian lang not supported (is it ok?)

### ISSUE THREAD

**Issue by akaRem** [loadfive/Knwl.js#68]
Tried a demo.
didnt fount anything from such text:
```
Привет! Поехали завтра в 12 часов в Москву. 
Давай встретимся в ресторане на маяковской дом 4 в 11:00.
Позвони мне по телефону +7 234 123 33 33 как будешь на месте.
```
is it ok?

**Comment by loadfive** [comment]
Hi, @akaRem! Right now, Knwl.js plugins have been focused on the English language. However, hopefully in the future there will be plugins available for a myriad of languages.

**Comment by akaRem** [comment]
@loadfive ok, thanks
