### ISSUE TITLE
Upper/lowercase are causing the places plugin to fail

### ISSUE THREAD

**Issue by edravis** [loadfive/Knwl.js#73]
Giving the following base string: "tourism trends in the Philippines".

*tourism trends in the Philippines*
 `knwl.get('places')` outputs:
```
[ { place: 'Philippines',
    preview: 'tourism trends in the Philippines',
    found: 2 } ]
```

but

*tourism trends in the philippines*
*Tourism Trends In The Philippines*
*TOURISMG TRENDS IN THE PHILIPPINES*
 `knwl.get('places')` outputs: **nothing** (empty array)

**Comment by loadfive** [comment]
Hi, @edravis! The ```places.js``` plugin has been updated to recognize a wider range of inputs.
