### ISSUE TITLE
Multi-lingual setup

### ISSUE THREAD

**Issue by NoelDavies** [loadfive/Knwl.js#77]
I know it's early days, but it'd be cool to start it now, to make things easier in the future. Being able to set what language the text is using, and then running any of the plugins with that specific language will make for more detailed analysis of processed text.

**Comment by loadfive** [comment]
Thanks for the idea @NoelDavies. The language may be set for Knwl.js instances now, which plugins can use to better adapt to input. Plugins can also specify which languages they officially support.

**Comment by NoelDavies** [comment]
Why not separate them out into folders? currently you've just added a languages object, with english set to true, surely it'd be better to a better recognised i18n setup with folder structure using AMD based loading?
