### ISSUE TITLE
Really picky JS Optimisation

### ISSUE THREAD

**Issue by MentalAtom** [loadfive/Knwl.js#80]
Hey,

I was just looking through the source code - Nice work! I just noticed a really small JS tweak you could do that would make it a little tidier. At the moment you do this a few times:

```javascript
var words = []; //make a copy of the rawWords array (otherwise, changes will be mirrored to knwl.words prop)
        for (var i = 0; i < rawWords.length; i++) {
            words[i] = rawWords[i];
        }
```

When you could do either:
`var words = rawWords.concat([]);` or `var words = rawWords.slice(0);`

As I say, it really doesn't matter too much... but clean code is happy code :smile: and I doubt the performance impact (if any) is significant.

**Comment by NoelDavies** [comment]
Hey man, can you submit a pull request for this?

**Comment by loadfive** [comment]
Hey, @MentalAtom, thanks for your pickiness! :) Your suggestions have been implemented.

**Comment by MentalAtom** [comment]
No worries, I'll have another look this evening and see if I spot anything else :)
