### ISSUE TITLE
Generate browser builds on release

### ISSUE THREAD

**Issue by thomastuts** [loadfive/Knwl.js#81]
Just wondering if it wouldn't be better if you added browser support by generating a browser release using Browserify yourselves (using the `standalone` option), and then optionally publishing the package to Bower too?

That way people can consume Knwl.js on the frontend using either method without having to force them to make a browserify build themselves.

If you'd like, I could set up a PR with a basic Gulp system to get the ball rolling?

**Comment by loadfive** [comment]
Hi, @thomastuts! The browser builds for Knwl.js are available in the ```./dist``` directory.
